
%myDir = 'D:\Tesi\covid19-classification-HC-features\code\trainedClassifiers'; %gets directory

myDir = 'D:\Tesi\covid19-classification-HC-features\code\TrainedMaxiFeaturesEnsembles'; %gets directory
myFiles = dir(fullfile(myDir,'\*.mat')); %gets all wav files in struct
myDirFeatures = 'D:\Tesi\covid19-classification-HC-features\code\FeaturesCNNHC\test'; %gets directory
myFilesFeatures = dir(fullfile(myDirFeatures,'\*.mat')); %gets all wav files in struct
for k = 1:length(myFiles)
    
    baseFileName = myFiles(k).name;
    fullFileName = fullfile(baseFileName);
    baseFileNameFeatures = myFilesFeatures(k).name;
    fullFileNameFeatures = fullfile(baseFileNameFeatures);
    fprintf('%s%s\n', "Inizio ",fullFileName);
   load(fullFileName);
    %load(strcat("D:\Tesi\covid19-classification-HC-features\code\FeaturesSingleCpu\test\",classifier.usedFeature,"_test_table.mat"));
    %load('D:\Tesi\covid19-classification-HC-features\code\FeaturesCNNHC\test\googleNet_HC_Test.mat')
    load(fullFileNameFeatures);
    testingTable=testingTableIteration;
    % all of your actions for filtering and plotting go here
    
    
    %testingTable.Properties.VariableNames{'Var1'} = 'labels';
    %testingTable.Properties.VariableNames{'Var2'} = 'features';
    %crea matrice confusione e statistiche
    confusion = confusionmat(testingTable.labels,classifier.predictFcn(testingTable));
    [stats, texMacro, texMicro] = computeStats(confusion);
    %modifico la table
    modifiedTable = splitvars(stats,'classes','NewVariableNames',{'covid-19','normal','pneumonia'});
    mA=table2array(modifiedTable);
    %formattazione file
    fileID = fopen('ReportCNNHCALL.txt','a');
    fprintf(fileID,['\\begin{table}[htbp]\n',...
        '\\centering\n',...
        '\\begin{tabular}{|p{2.9cm}||p{2cm}|p{2cm}|p{2cm}|p{2.5cm}|p{2.5cm}|}\n',...
        '\\hline\n',...
        'Nome & COVID-19 & Normale & Polmonite & Macro Avg & Micro Avg\\\\\n',...
        '\\hline\n',...
        'True Positive & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'False Positive & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'False Negative & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'True Negative & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'Precision & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'Sensitivity & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'Spefificaticy & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'Accuracy & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'F-measure & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'MAvG & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        'MAvA & %s & %s & %s & %s & %s\\\\\n',...
        '\\hline\n',...
        '\\end{tabular}\n',...
        '\\caption{%s}\n',...
        '\\label{tab:%s}\n',...
        '\\end{table}\n\\\\\\\\'
        ],mA(1,2),mA(1,3),mA(1,4),mA(1,5),mA(1,6)...Chiedo venia per lo stampino
        ,mA(2,2),mA(2,3),mA(2,4),mA(2,5),mA(2,6)...
        ,mA(3,2),mA(3,3),mA(3,4),mA(3,5),mA(3,6)...
        ,mA(4,2),mA(4,3),mA(4,4),mA(4,5),mA(4,6)...
        ,mA(5,2),mA(5,3),mA(5,4),mA(5,5),mA(5,6)...
        ,mA(6,2),mA(6,3),mA(6,4),mA(6,5),mA(6,6)...
        ,mA(7,2),mA(7,3),mA(7,4),mA(7,5),mA(7,6)...
        ,mA(8,2),mA(8,3),mA(8,4),mA(8,5),mA(8,6)...
        ,mA(9,2),mA(9,3),mA(9,4),mA(9,5),mA(9,6)...
        ,mA(10,2),mA(10,3),mA(10,4),mA(10,5),mA(10,6)...
        ,mA(11,2),mA(11,3),mA(11,4),mA(11,5),mA(11,6)...
        ,baseFileName,baseFileName);
    fclose(fileID);
    fprintf('%s%s\n', "Fine ",fullFileName);
end
